name: PR comment

on:
  - pull_request
jobs:
  comment:
    runs-on: windows-latest
    steps:
      - uses: jcbalbuena/Test@${{ github.sha }}
      - name: Create a PR comment
        with:
          issue_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      