name: PR comment

on:
  - pull_request
jobs:
  comment:
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - name: Create a PR comment
        uses: jcbalbuena/Test@main
        with:
          issue_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      