name: PR comment

on:
  - pull_request
jobs:
  permissions:
    contents: 'read'
    id-token: 'write'
  comment:
    runs-on: windows-latest
    steps:
      - name: Create a PR comment
        uses: jcbalbuena/Test@main
        with:
          issue_number: ${{ github.event.number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      